In [1]:
import pandas as pd
pd.set_option('max_rows',2000)
df = pd.read_csv('error_sample.csv',header = 0, names = ['name', 'address','price-range','country','style','likes','review','bookmark','discount_info'])
df=df.drop_duplicates(subset = 'address')

In [9]:
mapping = {
    '$101-200': 200,
    '$201-400': 400,
    '$401-800': 800,
    '$51-100': 100,
    '$50以下': 50,
    '$101.00': 100,
}
def convert_price(x):
    return mapping[x]
df['price-level']=df['price-range'].apply(convert_price)

200    228
400    166
100     56
800     26
50       3
Name: price-level, dtype: int64

In [11]:
mapping = {
    '韓國菜': 200,
    '$201-400': 400,
    '$401-800': 800,
    '$51-100': 100,
    '$50以下': 50,
    '$101.00': 100,
}
def convert_price(x):
    return mapping[x]
df['price-level']=df['price-range'].apply(convert)

西式          92
日本菜         83
多國菜         42
意大利菜        37
港式          35
粵菜 (廣東)     27
泰國菜         24
韓國菜         20
法國菜         18
美國菜         14
西班牙菜        10
川菜 (四川)     10
越南菜          8
意大利          8
台灣菜          8
德國菜          6
印度菜          6
英國菜          6
比利時菜         4
韩国菜          3
京菜 (官府菜)     3
京川滬          2
澳洲菜          2
湘菜 (湖南)      1
印尼菜          1
葡國菜          1
土耳其菜         1
秘魯菜          1
俄國菜          1
潮州菜          1
滬菜 (上海)      1
荷蘭菜          1
新加坡菜         1
蒙古菜          1
Name: country, dtype: int64

In [21]:
df['style'].value_counts()

火鍋                   56
海鮮                   47
壽司/刺身                35
甜品/糖水                28
薄餅                   22
酒                    20
咖啡店                  15
自助餐                  13
All Day Breakfast    12
中菜館                  11
扒房                   11
串燒                   10
西式                   10
酒吧                   10
法國菜                   9
泰國菜                   9
烤肉                    9
多國菜                   8
西餐廳                   8
素食                    8
日式放題                  8
漢堡包                   7
Fine Dining           6
點心                    5
三文治                   5
粉麵/米線                 5
咖喱                    5
西式糕點                  4
酒店餐廳                  4
沙律                    4
韓式炸雞                  4
無肉餐單                  3
西班牙菜                  3
樓上cafe                3
湯品                    3
私房菜                   3
拉麵                    3
比利時菜                  2
適合大夥人                 2
爐端燒                   2
燒烤                    2
同客食飯                  2
山珍海味                  2
韓燒                    2
鐵板燒                   2
包場派對                  2
荷蘭菜                   1
韓國菜                   1
台式飲品                  1
粥品                    1
意大利菜                  1
燒臘                    1
新加坡菜                  1
印度菜                   1
蠔吧                    1
麵包店                   1
果汁                    1
日本菜                   1
浪漫情調                  1
地中海菜                  1
藥膳                    1
咪嘥嘢食店                 1
社企餐廳                  1
中式包點                  1
德國菜                   1
土耳其菜                  1
Name: style, dtype: int64

In [22]:
df['likes'].value_counts()

114.0    7
10.0     7
8.0      6
90.0     5
6.0      5
82.0     5
40.0     5
70.0     5
151.0    5
57.0     5
58.0     4
64.0     4
94.0     4
55.0     4
84.0     4
25.0     4
48.0     4
36.0     4
86.0     4
27.0     4
93.0     4
74.0     4
118.0    4
39.0     4
135.0    4
157.0    4
159.0    4
170.0    4
60.0     3
1.0      3
72.0     3
50.0     3
91.0     3
77.0     3
29.0     3
97.0     3
208.0    3
5.0      3
21.0     3
130.0    3
152.0    3
129.0    3
119.0    3
87.0     3
163.0    3
195.0    3
96.0     3
98.0     3
80.0     3
67.0     3
187.0    3
89.0     3
83.0     3
237.0    3
216.0    3
104.0    3
148.0    3
20.0     3
9.0      3
4.0      3
42.0     3
56.0     3
69.0     3
45.0     3
41.0     3
19.0     3
2.0      2
141.0    2
108.0    2
189.0    2
51.0     2
34.0     2
113.0    2
24.0     2
142.0    2
280.0    2
107.0    2
95.0     2
407.0    2
337.0    2
139.0    2
15.0     2
122.0    2
191.0    2
116.0    2
138.0    2
145.0    2
177.0    2
115.0    2
165.0    2
172.0    2
174.0    2
146.0    2
155.0    2
61.0     2
251.0    2
99.0     2
221.0    2
28.0     2
63.0     2
62.0     2
262.0    2
76.0     2
78.0     2
240.0    2
7.0      2
226.0    2
276.0    2
31.0     2
16.0     2
132.0    2
43.0     2
35.0     2
235.0    2
231.0    1
168.0    1
272.0    1
302.0    1
414.0    1
144.0    1
205.0    1
250.0    1
238.0    1
178.0    1
380.0    1
202.0    1
200.0    1
184.0    1
484.0    1
490.0    1
230.0    1
503.0    1
432.0    1
450.0    1
233.0    1
336.0    1
437.0    1
190.0    1
508.0    1
470.0    1
301.0    1
210.0    1
375.0    1
320.0    1
239.0    1
258.0    1
270.0    1
192.0    1
223.0    1
286.0    1
268.0    1
185.0    1
358.0    1
396.0    1
304.0    1
312.0    1
481.0    1
444.0    1
234.0    1
222.0    1
236.0    1
295.0    1
350.0    1
173.0    1
365.0    1
207.0    1
362.0    1
175.0    1
260.0    1
300.0    1
247.0    1
321.0    1
199.0    1
176.0    1
131.0    1
33.0     1
26.0     1
85.0     1
109.0    1
59.0     1
73.0     1
53.0     1
101.0    1
38.0     1
71.0     1
49.0     1
44.0     1
66.0     1
54.0     1
88.0     1
117.0    1
65.0     1
37.0     1
153.0    1
487.0    1
257.0    1
371.0    1
285.0    1
281.0    1
277.0    1
279.0    1
311.0    1
309.0    1
383.0    1
305.0    1
381.0    1
415.0    1
409.0    1
341.0    1
574.0    1
369.0    1
549.0    1
125.0    1
92.0     1
161.0    1
156.0    1
123.0    1
150.0    1
214.0    1
134.0    1
120.0    1
102.0    1
133.0    1
171.0    1
198.0    1
147.0    1
215.0    1
164.0    1
188.0    1
179.0    1
162.0    1
218.0    1
211.0    1
126.0    1
283.0    1
194.0    1
693.0    1
203.0    1
13.0     1
22.0     1
3.0      1
11.0     1
14.0     1
121.0    1
18.0     1
204.0    1
46.0     1
388.0    1
228.0    1
79.0     1
112.0    1
110.0    1
47.0     1
137.0    1
436.0    1
Name: likes, dtype: int64